'use client';

import React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { UserRole } from '@/lib/types';
import { cn } from '@/lib/utils';

interface AdminSidebarProps {
  userRole: UserRole;
  userName: string;
  onLogout: () => void;
}

interface NavLink {
  label: string;
  href: string;
  icon: string;
  roles: UserRole[];
}

const navLinks: NavLink[] = [
  { label: 'Dashboard', href: '/admin', icon: '📊', roles: ['ADMIN', 'MARKETING', 'SALES', 'FINANCE', 'TECHNICAL', 'SUPPORT', 'READ_ONLY'] },
  { label: 'Leads', href: '/admin/leads', icon: '🎯', roles: ['ADMIN', 'SALES'] },
  { label: 'Pipeline', href: '/admin/pipeline', icon: '🔄', roles: ['ADMIN', 'SALES', 'MARKETING'] },
  { label: 'Contacts', href: '/admin/contacts', icon: '👥', roles: ['ADMIN', 'SALES', 'SUPPORT'] },
  { label: 'Automations', href: '/admin/automations', icon: '⚡', roles: ['ADMIN', 'SALES', 'MARKETING'] },
  { label: 'Knowledge Base', href: '/admin/knowledge', icon: '📚', roles: ['ADMIN', 'SUPPORT', 'TECHNICAL', 'SALES'] },
  { label: 'AI Insights', href: '/admin/insights', icon: '🧠', roles: ['ADMIN', 'MARKETING'] },
  { label: 'Audit Log', href: '/admin/audit', icon: '🔒', roles: ['ADMIN'] },
];

export function AdminSidebar({ userRole, userName, onLogout }: AdminSidebarProps) {
  const pathname = usePathname();
  const filteredLinks = navLinks.filter(link => link.roles.includes(userRole));

  return (
    <aside className="admin-sidebar">
      {/* Logo */}
      <div className="admin-sidebar-logo">
        <Link href="/admin" className="admin-logo-link">
          <span className="admin-logo-icon">⚡</span>
          <span className="admin-logo-text">3E Admin</span>
        </Link>
      </div>

      {/* Navigation */}
      <nav className="admin-sidebar-nav">
        {filteredLinks.map(link => (
          <Link
            key={link.href}
            href={link.href}
            className={cn(
              'admin-nav-link',
              (pathname === link.href || (link.href !== '/admin' && pathname?.startsWith(link.href))) && 'admin-nav-active'
            )}
          >
            <span className="admin-nav-icon">{link.icon}</span>
            <span className="admin-nav-label">{link.label}</span>
          </Link>
        ))}
      </nav>

      {/* User & Logout */}
      <div className="admin-sidebar-footer">
        <div className="admin-user-info">
          <div className="admin-user-avatar">{userName.charAt(0).toUpperCase()}</div>
          <div className="admin-user-details">
            <span className="admin-user-name">{userName}</span>
            <span className="admin-user-role">{userRole}</span>
          </div>
        </div>
        <button onClick={onLogout} className="admin-logout-btn">
          Sign Out
        </button>
        <Link href="/" className="admin-back-link">
          ← Back to Website
        </Link>
      </div>
    </aside>
  );
}

// ===== REUSABLE ADMIN COMPONENTS =====

export function DashboardCard({ title, value, change, icon, color }: {
  title: string;
  value: string | number;
  change?: number;
  icon: string;
  color?: string;
}) {
  return (
    <div className="admin-kpi-card" style={{ borderTopColor: color || 'var(--primary-600)' }}>
      <div className="admin-kpi-header">
        <span className="admin-kpi-icon">{icon}</span>
        <span className="admin-kpi-title">{title}</span>
      </div>
      <div className="admin-kpi-value">{typeof value === 'number' ? value.toLocaleString() : value}</div>
      {change !== undefined && change !== 0 && (
        <div className={cn('admin-kpi-change', change > 0 ? 'admin-kpi-positive' : 'admin-kpi-negative')}>
          {change > 0 ? '↑' : '↓'} {Math.abs(change).toFixed(1)}% vs prev period
        </div>
      )}
    </div>
  );
}

export function LeadScoreBadge({ tier, score }: { tier: 'HOT' | 'WARM' | 'COLD'; score: number }) {
  const classes: Record<string, string> = {
    HOT: 'admin-score-hot',
    WARM: 'admin-score-warm',
    COLD: 'admin-score-cold',
  };
  return (
    <span className={cn('admin-score-badge', classes[tier])}>
      {tier} ({score})
    </span>
  );
}

export function AIDraftBanner() {
  return (
    <div className="admin-ai-draft-banner">
      <span className="admin-ai-draft-icon">⚠️</span>
      <span className="admin-ai-draft-text">
        <strong>AI-GENERATED DRAFT</strong> — This content was generated by AI and requires human review before any external communication.
      </span>
    </div>
  );
}

export function AIInsightCard({ insight }: { insight: { type: string; title: string; description: string; confidence: number; sources: string[] } }) {
  const typeIcons: Record<string, string> = {
    trend: '📈',
    anomaly: '⚠️',
    opportunity: '💡',
    risk: '🔴',
  };

  return (
    <div className="admin-insight-card">
      <div className="admin-insight-header">
        <span className="admin-insight-icon">{typeIcons[insight.type] || '📊'}</span>
        <span className="admin-insight-title">{insight.title}</span>
        <span className="admin-insight-confidence">{Math.round(insight.confidence * 100)}% confidence</span>
      </div>
      <p className="admin-insight-desc">{insight.description}</p>
      <div className="admin-insight-sources">
        Sources: {insight.sources.join(', ')}
      </div>
    </div>
  );
}

export function EmptyState({ icon, title, description }: { icon: string; title: string; description: string }) {
  return (
    <div className="admin-empty-state">
      <span className="admin-empty-icon">{icon}</span>
      <h3 className="admin-empty-title">{title}</h3>
      <p className="admin-empty-desc">{description}</p>
    </div>
  );
}

export function LoadingState({ message }: { message?: string }) {
  return (
    <div className="admin-loading-state">
      <div className="admin-loading-spinner" />
      <span className="admin-loading-text">{message || 'Loading...'}</span>
    </div>
  );
}

export function ErrorState({ message, onRetry }: { message: string; onRetry?: () => void }) {
  return (
    <div className="admin-error-state">
      <span className="admin-error-icon">❌</span>
      <h3 className="admin-error-title">Something went wrong</h3>
      <p className="admin-error-desc">{message}</p>
      {onRetry && (
        <button onClick={onRetry} className="admin-error-retry">Try Again</button>
      )}
    </div>
  );
}

export function StageBadge({ stage }: { stage: string }) {
  const colors: Record<string, string> = {
    NEW_LEAD: '#3b82f6',
    QUALIFIED: '#8b5cf6',
    DISCOVERY: '#6366f1',
    QUOTE_REQUESTED: '#f59e0b',
    QUOTE_SENT: '#f97316',
    NEGOTIATION: '#ef4444',
    WON: '#10b981',
    LOST: '#6b7280',
    CUSTOMER: '#059669',
    NEW: '#3b82f6',
    CLOSED: '#6b7280',
  };

  const labels: Record<string, string> = {
    NEW_LEAD: 'New Lead',
    QUALIFIED: 'Qualified',
    DISCOVERY: 'Discovery',
    QUOTE_REQUESTED: 'Quote Requested',
    QUOTE_SENT: 'Quote Sent',
    NEGOTIATION: 'Negotiation',
    WON: 'Won',
    LOST: 'Lost',
    CUSTOMER: 'Customer',
    NEW: 'New',
    CLOSED: 'Closed',
  };

  return (
    <span
      className="admin-stage-badge"
      style={{ backgroundColor: `${colors[stage] || '#6b7280'}20`, color: colors[stage] || '#6b7280', borderColor: `${colors[stage] || '#6b7280'}40` }}
    >
      {labels[stage] || stage}
    </span>
  );
}
