'use client';

import React, { useState, useEffect } from 'react';
import { AIInsightCard, LoadingState, EmptyState } from '@/components/admin/AdminComponents';

interface Insight {
  type: string;
  title: string;
  description: string;
  confidence: number;
  sources: string[];
  metric?: string;
  value?: number;
  comparison?: string;
}

export default function AdminInsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [loading, setLoading] = useState(true);
  const [generatedAt, setGeneratedAt] = useState('');

  useEffect(() => { load(); }, []);

  async function load() {
    setLoading(true);
    try {
      const res = await fetch('/api/admin/insights');
      if (res.ok) {
        const data = await res.json();
        setInsights(data.insights || []);
        setGeneratedAt(data.generatedAt || '');
      }
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  }

  if (loading) return <LoadingState message="Generating AI insights..." />;

  return (
    <div className="admin-page">
      <div className="admin-page-header">
        <div>
          <h1 className="admin-page-title">🧠 AI Insights</h1>
          <p className="admin-page-subtitle">
            Data-driven observations • {insights.length} insights
            {generatedAt && ` • Generated ${new Date(generatedAt).toLocaleString()}`}
          </p>
        </div>
        <button onClick={load} className="admin-refresh-btn">🔄 Refresh</button>
      </div>

      {insights.length === 0 ? (
        <EmptyState icon="🧠" title="No Insights Yet" description="AI insights are generated from real data patterns. As more leads and orders accumulate, insights will appear here automatically." />
      ) : (
        <div className="admin-insights-grid">
          {insights.map((insight, i) => (
            <AIInsightCard key={i} insight={insight} />
          ))}
        </div>
      )}

      <div className="admin-section admin-disclaimer">
        <p className="admin-disclaimer-text">
          ℹ️ Insights are generated by AI analysis of your business data. They are advisory and should be validated by human judgement before making business decisions.
        </p>
      </div>
    </div>
  );
}
